name: certbot-dns-mydnsjp
summary: Authenticator plugin for certbot to handle dns-01 challenge with MyDNS.JP.
description: Authenticator plugin for certbot to handle dns-01 challenge with MyDNS.JP.
confinement: strict
grade: stable
base: core20
adopt-info: certbot-dns-mydnsjp
architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

parts:
  certbot-dns-mydnsjp:
    plugin: python
    source: .
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version `/usr/bin/python3  -m setuptools_scm | sed -E "s/Guessed\s+Version\s+//"`
    build-environment:
      - SNAP_BUILD: "True"
    requirements:
      - requirements.txt
    build-packages:
      - python3-dev
      - python3-setuptools-scm
      - git
  certbot-metadata:
    plugin: dump
    source: .
    stage: [ setup.py, certbot-shared ]
    override-pull: |
      snapcraftctl pull
      mkdir -p $SNAPCRAFT_PART_SRC/certbot-shared

slots:
  certbot:
    interface: content
    content: certbot-1
    read:
      - $SNAP/lib/python3.8/site-packages

plugs:
  certbot-metadata:
    interface: content
    content: metadata-1
    target: $SNAP/certbot-shared
